#cloud-config

# hostname
fqdn: demo

# SSH and users
users:
  - name: admin
    groups: sudo
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh-authorized-keys:
      - ssh-rsa

# Networking
resolv_conf:
  nameserver:
    - '8.8.8.8'

network:
  version: 2
  ethernets:
    ens33:
      addresses: [10.0.0.10/24]
      dhcp4: no
      optional: true

packages:
  - openjdk-17-jdk
  - mysql-server

runcmd:
  - iptables -t nat -A PREROUTING -p tcp --dport 8080 -j REDIRECT --to-port 80

datasource_list: [ Azure ]
datasource:
